In [16]:
import numpy as np 
import statsmodels.api as sm
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import mean_absolute_error
import statsmodels.api as sm

In [17]:
df = pd.read_csv(r'/home/infinitex/Desktop/JupiterNotebook/Asgn 12/50_Startups - 50_Startups.csv')

In [18]:
df

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [19]:
X = df.iloc[:,0:3]
Y = df.iloc[:,4]

In [20]:
#TRAIN TEST SPLIT
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=42)
X_train, Y_train, X_test, Y_test

(    R&D Spend  Administration  Marketing Spend
 46    1315.46       115816.21        297114.46
 47       0.00       135426.92             0.00
 15  114523.61       122616.84        261776.23
 9   123334.88       108679.17        304981.62
 16   78013.11       121597.55        264346.06
 24   77044.01        99281.34        140574.81
 34   46426.07       157693.92        210797.67
 31   61136.38       152701.92         88218.23
 0   165349.20       136897.80        471784.10
 44   22177.74       154806.14         28334.72
 27   72107.60       127864.55        353183.81
 33   55493.95       103057.49        214634.81
 5   131876.90        99814.71        362861.36
 29   65605.48       153032.06        107138.38
 11  100671.96        91790.61        249744.55
 36   28663.76       127056.21        201126.82
 1   162597.70       151377.59        443898.53
 21   78389.47       153773.43        299737.29
 2   153441.51       101145.55        407934.54
 43   15505.73       127382.30         35534.17
 35   46014.02        85047.44        205517.64
 23   67532.53       105751.03        304768.73
 40   28754.33       118546.05        172795.67
 10  101913.08       110594.11        229160.95
 22   73994.56       122782.75        303319.26
 18   91749.16       114175.79        294919.57
 49       0.00       116983.80         45173.06
 20   76253.86       113867.30        298664.47
 7   130298.13       145530.06        323876.68
 42   23640.93        96189.63        148001.11
 14  119943.24       156547.42        256512.92
 28   66051.52       182645.56        118148.20
 38   20229.59        65947.93        185265.10,
 46     49490.75
 47     42559.73
 15    129917.04
 9     149759.96
 16    126992.93
 24    108552.04
 34     96712.80
 31     97483.56
 0     192261.83
 44     65200.33
 27    105008.31
 33     96778.92
 5     156991.12
 29    101004.64
 11    144259.40
 36     90708.19
 1     191792.06
 21    111313.02
 2     191050.39
 43     69758.98
 35     96479.51
 23    108733.99
 40     78239.91
 10    146121.95
 22    110352.25
 18    124266.90
 49     14681.40
 20    118474.03
 7     155752.60
 42     71498.49
 14    132602.65
 28    103282.38
 38     81229.06
 Name: Profit, dtype: float64,
     R&D Spend  Administration  Marketing Spend
 13   91992.39       135495.07        252664.93
 39   38558.51        82982.09        174999.30
 30   61994.48       115641.28         91131.24
 45    1000.23       124153.04          1903.93
 17   94657.16       145077.58        282574.31
 48     542.05        51743.15             0.00
 26   75328.87       144135.98        134050.07
 25   64664.71       139553.16        137962.62
 32   63408.86       129219.61         46085.25
 19   86419.70       153514.11             0.00
 12   93863.75       127320.38        249839.44
 4   142107.34        91391.77        366168.42
 37   44069.95        51283.14        197029.42
 8   120542.52       148718.95        311613.29
 3   144372.41       118671.85        383199.62
 6   134615.46       147198.87        127716.82
 41   27892.92        84710.77        164470.71,
 13    134307.35
 39     81005.76
 30     99937.59
 45     64926.08
 17    125370.37
 48     35673.41
 26    105733.54
 25    107404.34
 32     97427.84
 19    122776.86
 12    141585.52
 4     166187.94
 37     89949.14
 8     152211.77
 3     182901.99
 6     156122.51
 41     77798.83
 Name: Profit, dtype: float64)

In [21]:
#MULTIPLE LINEAR REGRESSION MODEL
from sklearn.linear_model import LinearRegression
slrmodel = LinearRegression()
slrmodel.fit(X_train, Y_train)
y_pred = slrmodel.predict(X_test)
y_pred

array([125929.76643064,  85309.27957154,  98725.42324585,  46484.71255869,
       128149.44889006,  52254.10608781, 108259.60604419, 100236.95511129,
        97329.66211336, 112266.92446679, 128040.757999  , 173245.63315614,
        93098.9917306 , 149431.70577454, 173241.12995982, 155245.82218748,
        76307.67035448])

In [22]:
 # Residuals
residuals =Y_test-y_pred

#MEAN ABSOLUTE ERROR
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(Y_test, y_pred)
mae

6503.356192847071

In [23]:
#ROUTE MEAN ABSOLUTE ERROR
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(Y_test, y_pred)
rmse = np.sqrt(mse)
rmse

8500.406284589773

In [24]:
#RSQUARE & RADJUSTED
import statsmodels.api as sm
X_train = sm.add_constant(X_train)
model = sm.OLS(Y_train, X_train).fit()
model.summary2().tables[0]

                     0                 1                    2           3
0               Model:               OLS      Adj. R-squared:       0.943
1  Dependent Variable:            Profit                 AIC:    704.9123
2                Date:  2023-11-03 14:16                 BIC:    710.8984
3    No. Observations:                33      Log-Likelihood:     -348.46
4            Df Model:                 3         F-statistic:       176.6
5        Df Residuals:                29  Prob (F-statistic):    1.00e-18
6           R-squared:             0.948               Scale:  9.8927e+07

In [25]:
# Linear regression model with one independent variable, observe R-Squared and Adj.R-sqaured
X = df.iloc[:, 0:1].values
Y= df.iloc[:,4].values
X = sm.add_constant(X)
model = sm.OLS(Y, X).fit()
model.summary2().tables[0]

                     0                 1                    2           3
0               Model:               OLS      Adj. R-squared:       0.945
1  Dependent Variable:                 y                 AIC:   1058.8730
2                Date:  2023-11-03 14:16                 BIC:   1062.6971
3    No. Observations:                50      Log-Likelihood:     -527.44
4            Df Model:                 1         F-statistic:       849.8
5        Df Residuals:                48  Prob (F-statistic):    3.50e-32
6           R-squared:             0.947               Scale:  8.8668e+07

In [26]:
# Linear regression model with two independent variable,observe R-Squared and Adj.R-sqaured
X = df.iloc[:, 0:2].values
Y= df.iloc[:,4].values
X = sm.add_constant(X)
model = sm.OLS(Y, X).fit()
model.summary2().tables[0]

                     0                 1                    2           3
0               Model:               OLS      Adj. R-squared:       0.946
1  Dependent Variable:                 y                 AIC:   1059.6637
2                Date:  2023-11-03 14:16                 BIC:   1065.3998
3    No. Observations:                50      Log-Likelihood:     -526.83
4            Df Model:                 2         F-statistic:       426.8
5        Df Residuals:                47  Prob (F-statistic):    7.29e-31
6           R-squared:             0.948               Scale:  8.8390e+07

In [27]:
# Linear regression model with three independent variable,observe R-Squared and Adj.R-sqaured
X = df.iloc[:, 0:3].values
Y= df.iloc[:,4].values
X = sm.add_constant(X)
model = sm.OLS(Y, X).fit()
model.summary2().tables[0]

                     0                 1                    2           3
0               Model:               OLS      Adj. R-squared:       0.948
1  Dependent Variable:                 y                 AIC:   1058.7715
2                Date:  2023-11-03 14:16                 BIC:   1066.4196
3    No. Observations:                50      Log-Likelihood:     -525.39
4            Df Model:                 3         F-statistic:       296.0
5        Df Residuals:                46  Prob (F-statistic):    4.53e-30
6           R-squared:             0.951               Scale:  8.5236e+07

In [28]:
#polynomial regression 
# Extract the independent variables (features) and the dependent variable (target)
X = df[['R&D Spend', 'Administration', 'Marketing Spend', 'State']]
y = df['Profit']

# Convert the 'State' column into dummy/indicator variables
X = pd.get_dummies(X, columns=['State'], drop_first=True)

# Split the data into a training set and a testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create polynomial features
degree = 2  # You can change the degree as needed
poly = PolynomialFeatures(degree=degree)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

# Create and train the polynomial regression model
model = LinearRegression()
model.fit(X_train_poly, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test_poly)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse:.2f}")
print(f"R-squared (R2) Score: {r2:.2f}")

Mean Squared Error: 80596654.09
R-squared (R2) Score: 0.90

In [39]:
#ROUTE MEAN ABSOLUTE ERROR
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
rmse

9054.922470470265

In [41]:
#RSQUARE & RADJUSTED
import statsmodels.api as sm
X_train = sm.add_constant(X_train)
model = sm.OLS(y_train, X_train).fit()
model.summary2().tables[0]

                     0                 1                    2           3
0               Model:               OLS      Adj. R-squared:       0.947
1  Dependent Variable:            Profit                 AIC:    853.2663
2                Date:  2023-11-03 14:30                 BIC:    863.3996
3    No. Observations:                40      Log-Likelihood:     -420.63
4            Df Model:                 5         F-statistic:       140.1
5        Df Residuals:                34  Prob (F-statistic):    1.13e-21
6           R-squared:             0.954               Scale:  9.3765e+07

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

# Extract the independent variables (features) and the dependent variable (target)
X = df[['R&D Spend', 'Administration', 'Marketing Spend', 'State']]
y = df['Profit']

# Convert the 'State' column into dummy/indicator variables
X = pd.get_dummies(X, columns=['State'], drop_first=True)

# Split the data into a training set and a testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features (optional but recommended for Ridge Regression)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Create and train the Ridge regression model
alpha = 1.0 
model = Ridge(alpha=alpha)
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse:.2f}")
print(f"R-squared (R2) Score: {r2:.2f}")

Mean Squared Error: 84731799.39
R-squared (R2) Score: 0.90

In [43]:
#ROUTE MEAN ABSOLUTE ERROR
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
rmse

9054.922470470265

In [42]:
#RSQUARE & RADJUSTED
import statsmodels.api as sm
X_train = sm.add_constant(X_train)
model = sm.OLS(y_train, X_train).fit()
model.summary2().tables[0]

                     0                 1                    2           3
0               Model:               OLS      Adj. R-squared:       0.947
1  Dependent Variable:            Profit                 AIC:    853.2663
2                Date:  2023-11-03 14:31                 BIC:    863.3996
3    No. Observations:                40      Log-Likelihood:     -420.63
4            Df Model:                 5         F-statistic:       140.1
5        Df Residuals:                34  Prob (F-statistic):    1.13e-21
6           R-squared:             0.954               Scale:  9.3765e+07

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

# Extract the independent variables (features) and the dependent variable (target)
X = df[['R&D Spend', 'Administration', 'Marketing Spend', 'State']]
y = df['Profit']
# Convert the 'State' column into dummy/indicator variables
X = pd.get_dummies(X, columns=['State'], drop_first=True)

# Split the data into a training set and a testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features (optional but recommended for Lasso Regression)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Create and train the Lasso regression model
alpha = 1.0  # You can adjust the regularization strength (alpha) as needed
model = Lasso(alpha=alpha)
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse:.2f}")
print(f"R-squared (R2) Score: {r2:.2f}")

Mean Squared Error: 81991620.95
R-squared (R2) Score: 0.90

In [37]:
#ROUTE MEAN ABSOLUTE ERROR
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
rmse

9054.922470470265

In [38]:
#RSQUARE & RADJUSTED
import statsmodels.api as sm
X_train = sm.add_constant(X_train)
model = sm.OLS(y_train, X_train).fit()
model.summary2().tables[0]

                     0                 1                    2           3
0               Model:               OLS      Adj. R-squared:       0.947
1  Dependent Variable:            Profit                 AIC:    853.2663
2                Date:  2023-11-03 14:27                 BIC:    863.3996
3    No. Observations:                40      Log-Likelihood:     -420.63
4            Df Model:                 5         F-statistic:       140.1
5        Df Residuals:                34  Prob (F-statistic):    1.13e-21
6           R-squared:             0.954               Scale:  9.3765e+07